### ISSUE TITLE
为什么我没看到一行 react 相关的代码?

### ISSUE THREAD

**Issue by uinz** [zhoutk/koadmin#1]
> Admin for web, written with Node.js, koa, reactjs. 一个网站后台通用管理平台，将包括RBAC权限管理、无限级菜单等基本常用的功能。

是准备用 服务端渲染吗?

**Comment by zhoutk** [comment]
个人项目，开发中，最近有些停顿，呵呵!

**Comment by uinz** [comment]
come on!
